### ISSUE TITLE
All-access authentication with gmail

### ISSUE THREAD

**Issue by 687** [SmartBotBlack/alienworldsbot#11]
Hi, i have an issue with your AW mining bot, i'm using the gmail.comaccounts to authorize to all-access.wax.io and the script stuck on

Click Login Page

Can you help me with this?

C:\Users\Nas\alienworldsbot>npm run mine

> alienworldsbot@1.0.0 mine C:\Users\Nas\alienworldsbot
> node ./dist/index.js

Proxies not found!
pxxxxn.txt: Run!
pxxxxn.txt: Browser is waiting in the launch queue
pxxxxn.txt: Browser run
pxxxxn.txt: Add cookies

pxxxxxn.txt: Click Login Page
pxxxxn.txt: Click Login Page
pxxxxxn.txt: Click Login Page

pixxxxxxn.txt:
```

[
{
    "domain": ".wax.io",
    "expirationDate": 1707369561,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_ga",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "there is an value",
    "id": 1
},
{
    "domain": ".wax.io",
    "expirationDate": 1738905173.393806,
    "hostOnly": false,
    "httpOnly": false,
    "name": "sid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "there is an value",
    "id": 2
},
{
    "domain": "wallet.wax.io",
    "expirationDate": 1665637387.179742,
    "hostOnly": true,
    "httpOnly": false,
    "name": "AWSALB",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "there is an value",
    "id": 3
}
]
```

        Please check again.

_Originally posted by @voodee in https://github.com/SmartBotBlack/alienworldsbot/issues/5#issuecomment-1190355103_

**Comment by abyssofbirds** [comment]
@687 
This problem occurs due to invalid cookies. 
You need to log in to wax in your personal browser and get the cookies from https://wallet.wax.io/dashboard.Please try again and let us know if the error occurs again.

**Comment by 687** [comment]
You were right, i have used the new cookies from the /dashboard made on incoginito mode and it works like a charm :)

But there is another problem with the counting:

dxxc@xxx.pl.txt: Mining Bonus: 0 TLM
dxxxec@xxx.pl.txt: ms until next mine: 0
dzxc@xxx.pl.txt: Browser sleep: -30sec
dxxc@xxx.pl.txt: Browser is waiting in the launch queue

**Comment by abyssofbirds** [comment]
@687 we fixed this bugs. Update the code to the current state and try again.

**Comment by 687** [comment]
@abyssofbirds Hi, i cannot check the new version becouse of the problem with 
pxxxxxn.txt: Click Login Page
pxxxxn.txt: Click Login Page
pxxxxxn.txt: Click Login Page

came back

How does the cookies work, do they expire in about a day?

Is there a way to simply login to bot with google credencials ??

I have 20 accounts to manage and i need to start about 4 instances of bot do they interfere somehow?

**Comment by abyssofbirds** [comment]
If you have 20 accounts, you need to manually login to Wax 20 times and take cookies from the /dashboard page. Cookies will be valid for approximately one week. After that, you will have to repeat the login again and take the cookies.

Unfortunately, we currently do not have the functionality of automatic logging (Google account or login-password) and taking cookies.

We updated the code yesterday, there were bugs before, we fixed them. You also need to download the latest version of the code.

**Comment by 687** [comment]
@abyssofbirds 

After update

> alienworldsbot@1.0.0 mine
> node ./dist/index.js

Proxies not found!
pxxxxxon.txt: Run!
pxxxxxon.txt: Browser is waiting in the launch queue
pxxxxxon.txt: Browser run
pxxxxxon.txt: Add cookies
pxxxxxon.txt: Click Login Page
pxxxxxon.txt: Start Mine
pxxxxxon.txt: Get Claim
pxxxxxon.txt: Approve Wax
pxxxxxon.txt: Start Mine
pxxxxxon.txt: Get Claim

And freezes here

After restart:

Proxies not found!
pxxxxxon.txt: Run!
pxxxxxon.txt: Browser is waiting in the launch queue
pxxxxxon.txt: Browser run
pxxxxxon.txt: Add cookies
pxxxxxon.txt: Click Login Page
pxxxxxon.txt: Start Mine
pxxxxxon.txt: Start Mine
pxxxxxon.txt: Start Mine
pxxxxxon.txt: Get Claim

and freeze

**Comment by 687** [comment]
@abyssofbirds 
There is an issue with the newly created wax accounts on old ones the bot works like a charm but with the fresh accounts
the 
Click Login page problem persist

also:
when the error pops out:

dxxx@gmail.com.txt: Throw Error
dxxx@gmail.com.txt: TimeoutError: waiting for selector `.react-ripples .button` failed: timeout 30000ms exceeded
dxxx@gmail.com.txt:  Can't take screenshot
[Error: ENOENT: no such file or directory, open 'C:\Users\Mxxxxx\Desktop\alienworldsbot2\alienworldsbot\errors\Sat Oct 08 2022 10:05:22 GMT+0200 (czas środkowoeuropejski letni)-Alien Worlds.png'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Mxxxx\\Desktop\\alienworldsbot2\\alienworldsbot\\errors\\Sat Oct 08 2022 10:05:22 GMT+0200 (czas środkowoeuropejski letni)-Alien Worlds.png'

**Comment by abyssofbirds** [comment]
After 30 or 60 seconds of inactivity the bot should display an error. Wait for this error.

There can be two problems here - a long loading of the approval window on the wax, or some problems with the account. Can you manually mine tlm on this account?

**Comment by abyssofbirds** [comment]
TimeoutError: waiting for selector .react-ripples .button - error from wax. We cannot fix this. 
Wax server not responding

**Comment by 687** [comment]
I know but its not the problem with the fresh ones. This was a one time problem with the old one but i mentioned it because of the screenshoot problem 

I can manually mine on the fresh account without problem 

@abyssofbirds 
Edit:
C:\Users\Mxxxx\Desktop\alienworldsbot2>cd "C:\Users\Mxxx\Desktop\alienworldsbot2\alienworldsbot2"

C:\Users\Mxxxxxy\Desktop\alienworldsbot2\alienworldsbot2>npm run mine

> alienworldsbot@1.0.0 mine
> node ./dist/index.js

Proxies not found!
fxxxx.txt: Run!
fxxxxx.txt: Browser is waiting in the launch queue
fxxxx.txt: Browser run
fxxxxx.txt: Add cookies
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page
fxxxxx.txt: Click Login Page

 i have waited about 3-4 minutes but no error pops out. 
The cookies was created just like the previous one so it doesnt seem to be a problem with them

**Comment by abyssofbirds** [comment]
As for screenshots - try to create a folder in the root of the project and name "errors".

As for endless clicks login page - we can't replicate this situation in our system. When running two accounts, everything works for us without any errors. We need some time to catch and fix this error.

**Comment by 687** [comment]
I have the errors folder i think that the name could be too long or maybe with spaces:
Sat Oct 08 2022 10:05:22 GMT+0200 (czas środkowoeuropejski letni)-Alien Worlds.png
> As for screenshots - try to create a folder in the root of the project and name "errors".
>

I have found the solution the error folder, it was read only after cloning from git. Makeing it read write fixed the issue.

i actually succesfully run the 1 instance with 5 accounts
and a 2nd instance with another 3 and cannot run more

Is there any way i can help solve this issue? I can connect with you somehow


edit: 

Does the time between browser sleeps shoud be randomized?? I always get the same timeframe:
Browser sleep: 3235sec on all accounts with the same settings

**Comment by voodee** [comment]
> I have the errors folder i think that the name could be too long or maybe with spaces: Sat Oct 08 2022 10:05:22 GMT+0200 (czas środkowoeuropejski letni)-Alien Worlds.png
> 
> > As for screenshots - try to create a folder in the root of the project and name "errors".
> 
> I have found the solution the error folder, it was read only after cloning from git. Makeing it read write fixed the issue.
> 
> i actually succesfully run the 1 instance with 5 accounts and a 2nd instance with another 3 and cannot run more
> 
> Is there any way i can help solve this issue? I can connect with you somehow
> 
> edit:
> 
> Does the time between browser sleeps shoud be randomized?? I always get the same timeframe: Browser sleep: 3235sec on all accounts with the same settings


> and a 2nd instance with another 3 and cannot run more

@687  Why don't they start? What are the errors in the console? What screenshots are there of the errors?

Please use only latin letters without spaces in file names.

**Comment by 687** [comment]
@voodee 

At the moment it doesnt pop any errors or screenshoots it just loops the Click Login Page even if im 100% sure that the cookies are generated good

> alienworldsbot@1.0.0 mine
> node ./dist/index.js

Proxies not found!
booz.txt: Run!
booz.txt: Browser is waiting in the launch queue
dup.txt: Run!
dup.txt: Browser is waiting in the launch queue
nnowag.txt: Run!
nnowag.txt: Browser is waiting in the launch queue
ser.txt: Run!
ser.txt: Browser is waiting in the launch queue
booz.txt: Browser run
dup.txt: Browser run
nnowag.txt: Browser run
ser.txt: Browser run
booz.txt: Add cookies
nnowag.txt: Add cookies
ser.txt: Add cookies
dup.txt: Add cookies
ser.txt: Click Login Page
nnowag.txt: Click Login Page
dup.txt: Click Login Page
booz.txt: Click Login Page
ser.txt: Waiting to recharge
ser.txt: Browser sleep: 1495sec
(node:9516) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
booz.txt: Click Login Page
nnowag.txt: Waiting to recharge
nnowag.txt: Browser sleep: 2515sec
booz.txt: Click Login Page
dup.txt: Waiting to recharge
dup.txt: Browser sleep: 2515sec
booz.txt: Click Login Page
booz.txt: Click Login Page
booz.txt: Click Login Page
booz.txt: Click Login Page
booz.txt: Click Login Page


those are 3 "Old" accounts and a booz is a new.

   
```
 // ***
      const [loginBtnPlace] = await page.$x("//p[contains(., 'Start Now')]");

      let isClickedClaim = false;
      let numberOfClickLogin = 0;

      if (loginBtnPlace !== undefined && numberOfClickLogin <= 3) {
        log("Click Login s");

        await loginBtnPlace.click();
        await pause(random(0, 4 * 1000));

        numberOfEmptyPasses = 0;
        numberOfClickLogin += 1;
        continue;
      }
      if (numberOfClickLogin >= 3) {
        throw new Error("Too many clicks on the login button");
      }

      // ***

```
Looks that those code doesn't stop the loop to throw an error

**Comment by abyssofbirds** [comment]
@687 did you launch `npm run build` after updating code?

**Comment by 687** [comment]
@abyssofbirds @voodee 
Yes i have build many times before run but `npm ci` drops some errors maybe there issue will lay here:

```
`C:\Users\Mxxxscy\Desktop\alienworldsbot2\alienworldsbot4>npm ci
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated puppeteer@10.2.0: Version no longer supported. Upgrade to @latest

added 353 packages, and audited 354 packages in 2m

47 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (5 moderate, 3 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.`
```



But when i run `npm audit fix --force`
```
C:\Users\Machowscy\Desktop\alienworldsbot2\alienworldsbot4>npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN audit Updating puppeteer to 18.2.1, which is a SemVer major change.

added 8 packages, removed 83 packages, changed 20 packages, and audited 279 packages in 29s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

i get the problems during `npm run build`

```
C:\Users\Mssssscy\Desktop\alienworldsbot2\alienworldsbot4>npm run build

> alienworldsbot@1.0.0 build
> tsc

src/task.ts:224:15 - error TS2684: The 'this' context of type 'ElementHandle<Node>' is not assignable to method's 'this' of type 'ElementHandle<Element>'.
  Type 'Node' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 110 more.

224         await loginBtnPlace.click();
                  ~~~~~~~~~~~~~

src/task.ts:243:15 - error TS2684: The 'this' context of type 'ElementHandle<Node>' is not assignable to method's 'this' of type 'ElementHandle<Element>'.

243         await claimBtn.click();
                  ~~~~~~~~

src/task.ts:275:26 - error TS2531: Object is possibly 'null'.

275             (element) => element.textContent,
                             ~~~~~~~

src/task.ts:324:15 - error TS2684: The 'this' context of type 'ElementHandle<Node>' is not assignable to method's 'this' of type 'ElementHandle<Element>'.

324         await mineStartBtn.click();
                  ~~~~~~~~~~~~


Found 4 errors.
```

To avoid errors i have downgraded the puppeteer 

`npm i puppeteer@13.2`

but still left with 

```fsaaxxx.txt: Click Login Page
fsaaxxx.txt: Click Login Page
fsaaxxx.txt: Click Login Page
fsaaxxx.txt: Click Login Page
fsaaxxx.txt: Click Login Page
fsaaxxx.txt: Click Login Page
fsaaxxx.txt: Click Login Page
fsaaxxx.txt: Click Login Page
fsaaxxx.txt: Click Login Page
```


EDIT2:
Proposed changes just for ergonomics :D

``log(`Start Mine ${new Date().toLocaleString()}`);``

``log(`Browser sleep: ${pauseTime / 1000}sec ${new Date().toLocaleString()}`);``

**Comment by 687** [comment]
Okay @voodee @abyssofbirds 
I have found the fix. On new acc before using the bot you need to login and tick 
`Automatically login into play.alienworlds.io` :
![obraz](https://user-images.githubusercontent.com/1196545/194755101-46b6e31f-7b66-416c-9a4f-88cab68b8324.png)

After this the bot work flawlessly

Please add the ergo changes i proposed  :)

``log(`Start Mine ${new Date().toLocaleString()}`);``

``log(`Browser sleep: ${pauseTime / 1000}sec ${new Date().toLocaleString()}`);``

And somehow the loop for `3 * Click Login Page = throw Error` should be fixed to avoid getting Rate Limited by Cloudflare (ie. when the cookie expire):
![obraz](https://user-images.githubusercontent.com/1196545/194755973-cd1ac5d1-96fc-4f3b-a6ce-2f92024fd2e6.png)

**Comment by voodee** [comment]
@687 Try using a proxy. If you already use them, try other ones.
