### ISSUE TITLE
Многопоток не стабильно работает.

### ISSUE THREAD

**Issue by DekaSKy** [SmartBotBlack/alienworldsbot#4]
![photo_2021-12-23_14-58-10](https://user-images.githubusercontent.com/77372383/147237379-d91bbb1a-c8ef-40d0-b163-0605248542b8.jpg)
Добрый день,бот делает первый круг майнинга и на последующих не может залогиниться.
Используется nodejs 12.0.0

**Comment by voodee** [comment]
Проблема не актуальна.
